### PR TITLE
suggested extension hourly data - total to be refactored

### PR DESCRIPTION
**Pull request by wicomulder**

### CODE REVIEW

**Comment by JrtPec** [comment]
Thanks for your contribution, I've merged your code!

Some comments:
Please don't use separate files in a separate folder next time. Just edit the actual project files in a separate branch. Now I had to figure out whatever you changed, and copy the code over. Not only is it tedious and error prone, but also now you don't get any attribution, since git thinks I have written that code.

I have also written a separate parser for the hourly data, since date and hour were in separate columns and needed to be put together.
About that: I don't understand exactly what KNMI mean when they say a measurement comes from the N'th hour in a day. Normally that makes sense, but I've downloaded data for 2020-03-29, a day that should only have 23 hours (daylight saving time switch!), and KNMI returned 24 data points. So I'm confused. Also, because of that, it is impossible to localize that dataframe, so returned timestamps are timezone-naive.

**Comment by wicomulder** [comment]
Hi Jan,

good to see. Yes, I completely agree with you about the 'loose files'.
I just wanted you to give you an impression; and expected the refactoring
and valid checkout-merge later on my side.
Too many projects and loosing the me-being concise.
But you already merge/refactored. Wonderful.
Next time I will perform better.

warm regards
Wico

**Comment by JrtPec** [comment]
Tip: pull requests now have the option to be marked as "Draft", this indicates that you're not quite ready for a merge just yet, and blocks the admin from performing the merge.

**Comment by wicomulder** [comment]
Its a world on itself. Thanks!
Currently I am involved in the field of Datascience/AI algorithms.... the
KNMI api of you/us will be used soon in in the field of climate-systems in
buildings.

**Comment by JrtPec** [comment]
Good to know! Keep up the good work.

**Pull request merged**
