### PR TITLE
Add forecast data

### PR DESCRIPTION
**Pull request by timotk**
### Why?
Forecast data can be a nice addition to this library.

### Parsing
To parse the forecast data I used `BeautifulSoup`.
The output format is a `DataFrame`.

### Usage
```
>>> knmi.get_forecast_dataframe()
            neerslag  neerslagkans  temp_max  temp_min  windkracht  \
datum                                                                
2018-03-23         1           0.3        10         4           4   
2018-03-24         1           0.4        11         3           2   
2018-03-25         1           0.3        10         3           3   
2018-03-26         2           0.4        10         1           3   
2018-03-27         7           0.7        10         2           4   
2018-03-28         9           0.9         9         6           4   

           windrichting  zonneschijn  
datum                                 
2018-03-23           ZW          0.1  
2018-03-24            Z          0.1  
2018-03-25            W          0.3  
2018-03-26            W          0.3  
2018-03-27           ZW          0.2  
2018-03-28           ZW          0.2  

```

### Assumptions
- Always get lowest temperature for minimum temperature and highest temperature for maximum temperature. This means that "Min. 3/4°" will result in 3 and "Max. 8/9°" will result in 9.
- Convert percentages to chances (0-1).
- Convert other values to integers.
- Create a datum index in `datetime` format.

### Problems
- Depends on the website HTML and not an API.
- Forecast data is not available in the same format as historical data. This makes them difficult to join.

Please let me know what you think!

### CODE REVIEW

**Comment by JrtPec** [comment]
Hey, great addition!

* There is no station selection, so I assume this data is from De Bilt? Are there also other stations available?
* I think we should try to align the dataframes of historical and forecasted data, so they can be joined easily.
Variable names are listed in `metadata.py`, so I think a simple renaming operation could suffice.

**Comment by timotk** [comment]
- It's just the data from http://knmi.nl/nederland-nu/weer/verwachtingen, so I guess it's averaged for the whole country. They don't show more precise forecasts I believe. They do have current measurements at http://knmi.nl/nederland-nu/weer/waarnemingen
- Unfortunately, not all the values match. For example, measured temperatures have 1 decimal place, while prediction do not have decimal places. For historic data, wind speed is in m/s, while forecasts have wind force. in This might make them difficult to join.

**Comment by JrtPec** [comment]
Merged in version 0.1.2!

Some additions:
* I added the argument `station`. The default is `260` (De Bilt), and no other values are supported for now, but this leaves room to add other stations in the future. I consider De Bilt to be the "standard" for the whole country.
* I managed to more-or-less align all variables to existing ones in the API (except 'neerslagkans', since this is unique for forecasts). To do this I added conversions from Beaufort to m/s and wind directions to degrees.
* I added the argument `variables`, allows you to select specific variable names, similar to the other method.

I discovered some more detailed forecasts with more stations via http://knmi.nl/nederland-nu/weer/waarschuwingen-en-verwachtingen/weer-en-klimaatpluim. I'll be creating an issue for if someone would like to figure out if that page could also be scraped.

**Comment by timotk** [comment]
Thanks for merging, great additional work!

**Pull request merged**
